/* PERSON
STUDENT
FIGHTER
INSTRUCTOR
CERTIFICATION
CONTACT
*/
CREATE DATABASE DOJO 
GO

USE DOJO 
GO 


CREATE TABLE CERTIFICATION (
	CertificationID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	CertificationName VARCHAR(50) NOT NULL, 
	CertificationDescr VARCHAR(500) NULL
)

CREATE TABLE MEMBERSHIP_TYPE (
	MembershipTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	MembershipName VARCHAR(50) NOT NULL, 
	MembershipTypeDescr VARCHAR(500) NULL, 
	AnnualCost MONEY NULL
)

CREATE TABLE MEMBERSHIP (
	MembershipID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MembershipName VARCHAR(50) NOT NULL, 
	MembershipStartDate DATE NOT NULL, 
	MembershipEndDate DATE NULL,
	MembershipDescr VARCHAR(500) NULL,
	MembershipTypeID INT FOREIGN KEY REFERENCES MEMBERSHIP_TYPE(MembershipTypeID) NOT NULL
)

CREATE TABLE STYLE (
	StyleID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	StyleName VARCHAR(50) NOT NULL, 
	StyleDescr VARCHAR(500) NULL
)

CREATE TABLE "RANK" (
	RankID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	RankName VARCHAR(50) NOT NULL, 
	RankDescr VARCHAR(500) NULL
)

CREATE TABLE RANK_STYLE (
	RankSytleID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	RankID INT FOREIGN KEY REFERENCES "RANK"(RankID) NOT NULL, 
	StyleID INT FOREIGN KEY REFERENCES STYLE(StyleID) NOT NULL
)

CREATE TABLE EVENT_TYPE (
	EventTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	EventTypeName VARCHAR(50) NOT NULL, 
	EventTypeDescr VARCHAR(500) NULL
)

CREATE TABLE "EVENT" (
	EventID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	EventName VARCHAR(50) NOT NULL, 
	EventDescr VARCHAR(500) NULL, 
	EventTypeID INT FOREIGN KEY REFERENCES EVENT_TYPE(EventTypeID) NOT NULL, 
	EventDate DATE
)

CREATE TABLE CONTACT (
	ContactID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Phone NUMERIC(11,0) NOT NULL, 
	Street VARCHAR(50) NOT NULL, 
	City VARCHAR(50) NOT NULL, 
	"State" VARCHAR(50) NOT NULL, 
	ZipCode NUMERIC(5,0) NOT NULL, 
	Email VARCHAR(50) NULL 
)

CREATE TABLE PERSON (
	PersonID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	FirstName VARCHAR(50) NOT NULL, 
	LastName VARCHAR(50) NOT NULL, 
	DateOfBirth DATE NULL, 
	MembershipID INT FOREIGN KEY REFERENCES MEMBERSHIP(MembershipID) NOT NULL, 
	ContactID INT FOREIGN KEY REFERENCES CONTACT(ContactID) NOT NULL, 
	RankID INT FOREIGN KEY REFERENCES "RANK"(RankID) NOT NULL 
)

CREATE TABLE STUDENT (
	PersonID INT FOREIGN KEY REFERENCES PERSON(PersonID) PRIMARY KEY NOT NULL, 
	StudentStartDate DATE NOT NULL, 
	StudentEndDate DATE NULL 
)

CREATE TABLE INSTRUCTOR (
	PersonID INT FOREIGN KEY REFERENCES PERSON(PersonID) PRIMARY KEY NOT NULL, 
	InstructorStartDate DATE NOT NULL, 
	InstructorEndDate DATE NULL,
	InstructorTitle VARCHAR(50) NOT NULL,
	CertificationID INT FOREIGN KEY REFERENCES CERTIFICATION(CertificationID) NOT NULL
)

CREATE TABLE FIGTHER (
	PersonID INT FOREIGN KEY REFERENCES PERSON(PersonID) PRIMARY KEY NOT NULL, 
	TotalMatches NUMERIC(4, 0) NOT NULL, 
	TotalWins NUMERIC(4, 0) NOT NULL, 
	FighterStyle VARCHAR(100) NULL, 
	FighterStartDate DATE NOT NULL, 
	FighterEndDate DATE NULL
)

CREATE TABLE EVENT_PERSON (
	EventPersonID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	PersonID INT FOREIGN KEY REFERENCES PERSON(PersonID) NOT NULL,
	EventID INT FOREIGN KEY REFERENCES "EVENT"(EventID) NOT NULL, 
)

CREATE TABLE CLASS_TYPE (
	ClassTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	ClassTypeName VARCHAR(50) NOT NULL,
	ClassTypeDescr VARCHAR(500) NULL
)

CREATE TABLE CLASS (
	ClassID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	ClassTypeID INT FOREIGN KEY REFERENCES CLASS_TYPE(ClassTypeID) NOT NULL, 
	ClassTime TIME NOT NULL, 
	ClassName VARCHAR(50) NOT NULL, 
	ClassDescr VARCHAR(500) NULL, 
	ClassBeginDate DATE NOT NULL, 
	ClassEndDate DATE NULL
)

CREATE TABLE PERSON_CLASS (
	PERSONClassID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	PeoplID INT FOREIGN KEY REFERENCES PERSON(PersonID) NOT NULL, 
	ClassID INT FOREIGN KEY REFERENCES CLASS(ClassID) NOT NULL, 
	ClassDate DATE NOT NULL
)

CREATE TABLE PAYMENT_TYPE (
	PaymentTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PaymentTypeName VARCHAR(50) NOT NULL, 
	PaymentTypeDescr VARCHAR(500) NULL,
)

CREATE TABLE PRODUCT_TYPE (
	ProductTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	ProductTypeName VARCHAR(50) NOT NULL, 
	ProductTypeDescr VARCHAR(500) NULL
)

CREATE TABLE INVENTORY_TYPE (
	InventoryTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	InventoryTypeName VARCHAR(50) NOT NULL, 
	InventoryTypeDescr VARCHAR(500) NULL
)

CREATE TABLE INVENTORY (
	InventoryID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Quantity NUMERIC(4,1) NOT NULL, 
	InventoryDescr VARCHAR(500) NULL, 
	InventoryTypeID INT FOREIGN KEY REFERENCES INVENTORY_TYPE(InventoryTypeID) NOT NULL 
)

CREATE TABLE PRODUCT (
	ProductID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	ProductName VARCHAR(50) NOT NULL, 
	ProductCost MONEY NOT NULL, 
	ProductDescr VARCHAR(500) NULL, 
	ProductTypeID INT FOREIGN KEY REFERENCES PRODUCT_TYPE(ProductTypeID) NOT NULL, 
	InventoryID INT FOREIGN KEY REFERENCES INVENTORY(InventoryID) NOT NULL
)

CREATE TABLE PAYMENT (
	Payment INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	PaymentTypeID INT FOREIGN KEY REFERENCES PAYMENT_TYPE(PaymentTypeID) NOT NULL,
	PersonID INT FOREIGN KEY REFERENCES PERSON(PersonID) NOT NULL, 
	Amount MONEY NULL, 
	PaymentDate DATE NULL, 
	ProductID INT FOREIGN KEY REFERENCES PRODUCT(ProductID) NULL
)



